server:
  port: 7002

#Eureka集群配置就是将7001注册到7002中,将7002注册到7001中,保证服务的高可用.
#访问集群是 http://eureka7001.com:7001/中有注册7002,http://eureka7002.com:7002/中有注册7001
eureka:
  instance:
    hostname: eureka7002.com #eureka服务端的实例名称
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #集群指向其它eureka
      defaultZone: http://eureka7001.com:7001/eureka/
      #单机就是7001自己
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    #server:
    #关闭自我保护机制，保证不可用服务被及时踢除,默认自我保护数开启的,90秒收不到服务的心跳踢出,这里修改成2秒
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000