#指定服务端口号
server:
  port: 8005

#指定服务名称
spring:
  application:
    name: consul-provider-paymentconsul
  #consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
